services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    #      - ./schema/schema.sql:/var/lib/mysql/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
